name:                ImageCompressor
version:             0.1.0.0
github:              "githubuser/ImageCompressor"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ImageCompressor#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels >= 3.3 && <= 3.3.5
- bytestring == 0.10.12.0
- directory == 1.3.6.0
- text == 1.2.4.1
- optparse-applicative == 0.16.1.0
- random == 1.2.0
library:
  source-dirs: src

executables:
  ImageCompressor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageCompressor
    - JuicyPixels >= 3.3 && <= 3.3.5

tests:
  ImageCompressor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageCompressor
